name: test
on: []
jobs:
  ready_edge:
    name: Ready Edge
    runs-on: ubuntu-latest
    steps:
      - name: Ready edge
        run: echo Hello, world!

      - name: Normalize Player Username
        run: echo Hello, world!
        
      - name: Fetch game information
        run: echo Hello, world!
