name: test
on:
  workflow_dispatch:
jobs:
  job1:
    name: Ready Edge
    runs-on: ubuntu-latest
    steps:
      - name: Ready edge
        run: echo Hello, world!
  job2:
    name: Normalize Player Username
    runs-on: ubuntu-latest
    steps:
      - name: Ready edge
        run: echo Hello, world!
