name: test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Ready edge
        run: echo Hello, world!

      - name: Normalize Player Username
        run: echo Hello, world!
        
      - name: Fetch game information
        run: echo Hello, world!
