name: test
on:
  workflow_dispatch:
jobs:
  job1:
    name: Ready Edge
    runs-on: ubuntu-latest
    steps:
      - name: Ready edge
        run: sleep 1m
  job2:
    name: Fetch game information
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Ready edge
        run: sleep 3s
  job3:
    name: Normalize Player Username
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Ready edge
        run: sleep 2s
